server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前的数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ceshi01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shangma.springCloud.entities # 所有实体类在所在包

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true